# Site settings
title: Hydra | Online
author: Benson Yu
email: benson(dot)yu12(at)gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experience Sharing
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://bensonyu.github.io" # the base hostname & protocol for your site
url: "http://gitweb.bensonyu.com"
twitter_username: YuYaobin
github_username:  BensonYu

# Build settings
markdown: kramdown
